import { FullProviderProfile, Tier, ClinicianType, Language, Condition, PatientDemographic, TrainingLevel } from "@/types";

export const states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"];
export const clinicianTypes: ClinicianType[] = ["Chiropractor", "Physical Therapist", "Athletic Trainer", "Massage Therapist", "Other"];
export const languages: Language[] = ["English", "Spanish", "French", "German", "Mandarin"];
export const radiusOptions = [5, 10, 25, 50, 100];
export const sortOptions = [
  { value: "premier-first", label: "Premier Providers First" },
  { value: "top-rated", label: "Top Rated" },
  { value: "most-reviewed", label: "Most Reviewed" },
];
export const conditions: Condition[] = ["Back Pain", "Neck Pain", "Headaches", "Sports Injuries", "Post-Surgical Rehab"];
export const patientDemographics: PatientDemographic[] = ["Athletes", "Pediatrics", "Geriatrics", "General Population"];

export const mockProviders: FullProviderProfile[] = [
    {
        id: "1",
        name: "Dr. John Doe",
        email: "john.doe@example.com",
        specialty: "Sports Medicine",
        bio: "Dr. John Doe is a certified Graston Technique provider with over 10 years of experience in treating sports-related injuries. He is passionate about helping athletes return to their peak performance.",
        experience: "10 years",
        education: "D.C. from Palmer College of Chiropractic",
        profileImage: "https://i.pravatar.cc/150?u=1",
        phone: "123-456-7890",
        website: "johndoechiro.com",
        location: "San Diego, CA",
        clinicAddress: "123 Wellness Way, San Diego, CA 92101",
        coordinates: { lat: 32.7157, lng: -117.1611 },
        tier: "Premier",
        clinicianType: "Chiropractor",
        gtCertifications: ["GTS", "Advanced"],
        services: ["Spinal Adjustments", "Graston Technique", "Rehabilitation"],
        languagesSpoken: ["English", "Spanish"],
        rating: 4.9,
        reviewCount: 120,
        isFavorite: false,
        trialStatus: "N/A",
        activity: 95,
        churnRisk: false,
        views: 4500,
        engagementScore: 92,
    },
    {
        id: "2",
        name: "Dr. Jane Smith",
        email: "jane.smith@example.com",
        specialty: "Physical Therapy",
        bio: "Dr. Jane Smith specializes in post-surgical rehabilitation and chronic pain management. She integrates the Graston Technique to accelerate recovery and improve patient outcomes.",
        experience: "8 years",
        education: "D.P.T. from University of Southern California",
        profileImage: "https://i.pravatar.cc/150?u=2",
        phone: "987-654-3210",
        website: "janesmithpt.com",
        location: "New York, NY",
        clinicAddress: "456 Health Ave, New York, NY 10001",
        coordinates: { lat: 40.7128, lng: -74.0060 },
        tier: "Preferred",
        clinicianType: "Physical Therapist",
        gtCertifications: ["Essential"],
        services: ["Manual Therapy", "Graston Technique", "Therapeutic Exercise"],
        languagesSpoken: ["English"],
        rating: 4.8,
        reviewCount: 85,
        isFavorite: true,
        trialStatus: "Active",
        activity: 78,
        churnRisk: false,
        views: 2800,
        engagementScore: 75,
    },
    {
        id: "3",
        name: "Dr. Emily White",
        email: "emily.white@example.com",
        specialty: "Chiropractic",
        bio: "A dedicated chiropractor focusing on family wellness and pediatric care.",
        experience: "5 years",
        education: "D.C. from Life University",
        profileImage: "https://i.pravatar.cc/150?u=3",
        phone: "555-123-4567",
        website: "emilywhitechiro.com",
        location: "Chicago, IL",
        clinicAddress: "789 State St, Chicago, IL 60605",
        coordinates: { lat: 41.8818, lng: -87.6232 },
        tier: "Free",
        clinicianType: "Chiropractor",
        gtCertifications: ["GTS"],
        services: ["Family Wellness", "Pediatric Adjustments"],
        languagesSpoken: ["English"],
        rating: 4.5,
        reviewCount: 45,
        isFavorite: false,
        trialStatus: "Expired",
        activity: 35,
        churnRisk: true,
        views: 1200,
        engagementScore: 40,
    },
    {
        id: "4",
        name: "Dr. Michael Brown",
        email: "michael.brown@example.com",
        specialty: "Athletic Training",
        bio: "Works with professional sports teams to prevent and treat injuries.",
        experience: "12 years",
        education: "M.S. in Athletic Training",
        profileImage: "https://i.pravatar.cc/150?u=4",
        phone: "555-987-6543",
        website: "mikebrownat.com",
        location: "Los Angeles, CA",
        clinicAddress: "101 Victory Lane, Los Angeles, CA 90012",
        coordinates: { lat: 34.0522, lng: -118.2437 },
        tier: "Premier",
        clinicianType: "Athletic Trainer",
        gtCertifications: ["Advanced"],
        services: ["Injury Prevention", "Performance Enhancement"],
        languagesSpoken: ["English"],
        rating: 5.0,
        reviewCount: 210,
        isFavorite: true,
        trialStatus: "N/A",
        activity: 98,
        churnRisk: false,
        views: 5102,
        engagementScore: 95,
    },
    {
        id: "5",
        name: "Sarah Chen, LMT",
        email: "sarah.chen@example.com",
        specialty: "Massage Therapy",
        bio: "Specializes in deep tissue and therapeutic massage, incorporating Graston to release facial restrictions.",
        experience: "7 years",
        education: "Licensed Massage Therapist",
        profileImage: "https://i.pravatar.cc/150?u=5",
        phone: "555-555-1212",
        website: "sarahchenmassage.com",
        location: "Seattle, WA",
        clinicAddress: "222 Pine St, Seattle, WA 98101",
        coordinates: { lat: 47.6062, lng: -122.3321 },
        tier: "Preferred",
        clinicianType: "Massage Therapist",
        gtCertifications: ["Essential"],
        services: ["Deep Tissue", "Myofascial Release"],
        languagesSpoken: ["English", "Mandarin"],
        rating: 4.9,
        reviewCount: 95,
        isFavorite: false,
        trialStatus: "N/A",
        activity: 82,
        churnRisk: false,
        views: 1980,
        engagementScore: 68,
    },
    {
        id: "6",
        name: "Dr. David Wilson",
        email: "david.wilson@example.com",
        specialty: "Physical Therapy",
        bio: "Focuses on geriatric care and mobility improvement.",
        experience: "15 years",
        education: "D.P.T. from Boston University",
        profileImage: "https://i.pravatar.cc/150?u=6",
        phone: "555-111-2222",
        website: "davidwilsonpt.com",
        location: "Boston, MA",
        clinicAddress: "333 Beacon St, Boston, MA 02116",
        coordinates: { lat: 42.3584, lng: -71.0636 },
        tier: "Free",
        clinicianType: "Physical Therapist",
        gtCertifications: ["GTS"],
        services: ["Geriatric PT", "Balance Training"],
        languagesSpoken: ["English"],
        rating: 4.7,
        reviewCount: 70,
        isFavorite: false,
        trialStatus: "N/A",
        activity: 55,
        churnRisk: false,
        views: 950,
        engagementScore: 50,
    },
    {
        id: "7",
        name: "Dr. Maria Garcia",
        email: "maria.garcia@example.com",
        specialty: "Chiropractic",
        bio: "Bilingual chiropractor serving the Miami area with a focus on holistic health.",
        experience: "6 years",
        education: "D.C. from Parker University",
        profileImage: "https://i.pravatar.cc/150?u=7",
        phone: "555-222-3333",
        website: "mariagarciadc.com",
        location: "Miami, FL",
        clinicAddress: "444 Ocean Dr, Miami, FL 33139",
        coordinates: { lat: 25.7907, lng: -80.1300 },
        tier: "Premier",
        clinicianType: "Chiropractor",
        gtCertifications: ["Advanced"],
        services: ["Holistic Health", "Nutritional Counseling"],
        languagesSpoken: ["English", "Spanish"],
        rating: 4.9,
        reviewCount: 150,
        isFavorite: true,
        trialStatus: "N/A",
        activity: 90,
        churnRisk: false,
        views: 3500,
        engagementScore: 88,
    },
    {
        id: "8",
        name: "Dr. Ben Carter",
        email: "ben.carter@example.com",
        specialty: "Physical Therapy",
        bio: "A PT helping weekend warriors in Austin stay active and pain-free.",
        experience: "4 years",
        education: "D.P.T. from Texas State University",
        profileImage: "https://i.pravatar.cc/150?u=8",
        location: "Austin, TX",
        clinicAddress: "555 Congress Ave, Austin, TX 78701",
        coordinates: { lat: 30.2672, lng: -97.7431 },
        tier: "Preferred",
        clinicianType: "Physical Therapist",
        gtCertifications: ["Essential"],
        services: ["Weekend Warrior Care", "Dry Needling"],
        languagesSpoken: ["English"],
        rating: 4.8,
        reviewCount: 60,
        isFavorite: false,
        trialStatus: "Active",
        activity: 70,
        churnRisk: false,
        views: 1500,
        engagementScore: 65,
    },
    {
        id: "9",
        name: "Dr. Olivia Martinez",
        email: "olivia.martinez@example.com",
        specialty: "Chiropractic",
        bio: "Specializing in prenatal and postnatal chiropractic care.",
        experience: "9 years",
        education: "D.C. from Logan University",
        profileImage: "https://i.pravatar.cc/150?u=9",
        location: "Denver, CO",
        clinicAddress: "666 Mountain View Rd, Denver, CO 80202",
        coordinates: { lat: 39.7392, lng: -104.9903 },
        tier: "Premier",
        clinicianType: "Chiropractor",
        gtCertifications: ["GTS", "Advanced"],
        services: ["Prenatal Care", "Webster Technique"],
        languagesSpoken: ["English"],
        rating: 5.0,
        reviewCount: 180,
        isFavorite: false,
        trialStatus: "N/A",
        activity: 96,
        churnRisk: false,
        views: 4800,
        engagementScore: 94,
    },
    {
        id: "10",
        name: "Tom Harris, LMT",
        email: "tom.harris@example.com",
        specialty: "Massage Therapy",
        bio: "Focused on clinical massage for chronic pain conditions.",
        experience: "11 years",
        education: "Licensed Massage Therapist",
        profileImage: "https://i.pravatar.cc/150?u=10",
        location: "Phoenix, AZ",
        clinicAddress: "777 Sun Valley Blvd, Phoenix, AZ 85001",
        coordinates: { lat: 33.4484, lng: -112.0740 },
        tier: "Free",
        clinicianType: "Massage Therapist",
        gtCertifications: ["Essential"],
        services: ["Clinical Massage", "Trigger Point Therapy"],
        languagesSpoken: ["English"],
        rating: 4.6,
        reviewCount: 55,
        isFavorite: false,
        trialStatus: "Expired",
        activity: 40,
        churnRisk: true,
        views: 800,
        engagementScore: 45,
    },
];

export const specialties = [...new Set(mockProviders.map(p => p.specialty).filter(Boolean))] as string[];