import { FullProviderProfile, ClinicianType, Language, Condition, PatientDemographic, Tier, TrainingLevel } from "@/types";

export const clinicianTypes: ClinicianType[] = ["Chiropractor", "Physical Therapist", "Athletic Trainer", "Massage Therapist", "Other", "Medical Doctor"];
export const languages: Language[] = ["English", "Spanish", "French", "German", "Mandarin", "Hindi", "Korean", "Italian"];
export const radiusOptions = [5, 10, 25, 50, 100];
export const specialties = [
    "Physical Therapy", "Chiropractic", "Occupational Therapy", "Sports Medicine",
    "Pain Management", "Rehabilitation", "Orthopedics", "Neurology", "Pediatrics",
    "Geriatrics", "Women's Health", "Manual Therapy", "Acupuncture", "Massage Therapy"
];
export const conditions: Condition[] = ["Back Pain", "Neck Pain", "Headaches", "Sports Injury", "Post-surgical Rehab", "Shoulder Pain", "Knee Pain", "Prenatal Therapy", "Ankle Rehab"];
export const patientDemographics: PatientDemographic[] = ["Athletes", "Pediatric", "Geriatric", "Adult", "Adolescent", "Pregnant Women"];

export const mockProviders: FullProviderProfile[] = [
    {
        id: "prov_001",
        name: "Dr. Alex Johnson",
        specialty: "Chiropractic",
        profileImage: "https://i.pravatar.cc/150?img=68",
        location: "Denver, CO",
        clinicAddress: "123 Main St, Denver, CO 80203",
        coordinates: { lat: 39.7392, lng: -104.9903 },
        tier: "Premier",
        clinicianType: "Chiropractor",
        gtCertifications: ["GTS", "Advanced"],
        services: ["Spinal Adjustments", "Graston Technique", "Rehabilitation"],
        languagesSpoken: ["English", "Spanish"],
        patientTypes: ["Adult", "Athletes"],
        conditionsTreated: ["Back Pain", "Neck Pain", "Headaches"],
        rating: 4.8,
        reviewCount: 120,
        isFavorite: false,
        can_compare: true,
        views: 1500,
        engagementScore: 85,
        trialStatus: 'N/A',
        churnRisk: false,
        activity: 100,
        accreditationLogos: [
            { name: "American Chiropractic Association", logoUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/American_Chiropractic_Association_logo.svg/1200px-American_Chiropractic_Association_logo.svg.png", url: "https://www.acatoday.org/" },
        ],
        testimonials: [
            { quote: "Dr. Johnson is amazing! My back pain is gone.", author: "John D.", rating: 5 },
            { quote: "Professional and effective treatment.", author: "Sarah K.", rating: 5 },
        ],
        faqs: [
            { question: "What is Graston Technique?", answer: "Graston Technique is an innovative, instrument-assisted soft tissue mobilization that enables clinicians to effectively address scar tissue and fascial restrictions." },
        ],
        galleryImages: [
            "https://images.unsplash.com/photo-1584820927466-09793f8a6982?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "https://images.unsplash.com/photo-1532635241-e91136613b1b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        ]
    },
    {
        id: "prov_002",
        name: "Dr. Jane Smith",
        specialty: "Physical Therapy",
        profileImage: "https://i.pravatar.cc/150?img=45",
        location: "Boulder, CO",
        clinicAddress: "456 Oak Ave, Boulder, CO 80302",
        coordinates: { lat: 40.0150, lng: -105.2705 },
        tier: "Premier",
        clinicianType: "Physical Therapist",
        gtCertifications: ["Essential"],
        services: ["Manual Therapy", "Graston Technique", "Therapeutic Exercise"],
        languagesSpoken: ["English"],
        patientTypes: ["Adult", "Geriatric"],
        conditionsTreated: ["Shoulder Pain", "Knee Pain"],
        rating: 4.9,
        reviewCount: 90,
        isFavorite: true,
        can_compare: true,
        views: 2500,
        engagementScore: 92,
        trialStatus: 'N/A',
        churnRisk: false,
        activity: 120,
        accreditationLogos: [
            { name: "American Physical Therapy Association", logoUrl: "https://www.apta.org/uploadedImages/APTAorg/About_Us/News/APTA_Logo_RGB.png", url: "https://www.apta.org/" },
        ],
        testimonials: [
            { quote: "Highly recommend Dr. Smith for physical therapy.", author: "Emily R.", rating: 5 },
        ],
        faqs: [
            { question: "Do you accept insurance?", answer: "Yes, we accept most major insurance plans. Please contact our office for details." },
        ],
        galleryImages: [
            "https://images.unsplash.com/photo-1576091160550-fd428796c874?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
            "https://images.unsplash.com/photo-1584820927466-09793f8a6982?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        ]
    },
    {
        id: "prov_003",
        name: "Dr. Michael Brown",
        specialty: "Sports Medicine",
        profileImage: "https://i.pravatar.cc/150?img=12",
        location: "Fort Collins, CO",
        clinicAddress: "789 Pine St, Fort Collins, CO 80521",
        coordinates: { lat: 40.5853, lng: -105.0844 },
        tier: "Preferred",
        clinicianType: "Physical Therapist",
        gtCertifications: ["GTS"],
        services: ["Graston Technique", "Therapeutic Exercises"],
        languagesSpoken: ["English"],
        patientTypes: ["Athletes"],
        conditionsTreated: ["Sports Injury", "Ankle Rehab"],
        rating: 4.7,
        reviewCount: 75,
        isFavorite: false,
        can_compare: true,
        views: 900,
        engagementScore: 78,
        trialStatus: 'N/A',
        churnRisk: false,
        activity: 80,
        accreditationLogos: [],
        testimonials: [],
        faqs: [],
    },
    {
        id: "prov_004",
        name: "Dr. Sarah Davis",
        specialty: "Occupational Therapy",
        profileImage: "https://i.pravatar.cc/150?img=23",
        location: "Colorado Springs, CO",
        clinicAddress: "101 Elm St, Colorado Springs, CO 80903",
        coordinates: { lat: 38.8342, lng: -104.8214 },
        tier: "Preferred",
        clinicianType: "Occupational Therapist",
        gtCertifications: ["Advanced"],
        services: ["Activities of Daily Living Training", "Graston Technique"],
        languagesSpoken: ["English", "French"],
        patientTypes: ["Pediatric", "Adult"],
        conditionsTreated: ["Shoulder Pain", "Post-surgical Rehab"],
        rating: 4.6,
        reviewCount: 60,
        isFavorite: false,
        can_compare: true,
        views: 700,
        engagementScore: 70,
        trialStatus: 'N/A',
        churnRisk: false,
        activity: 70,
        accreditationLogos: [],
        testimonials: [],
        faqs: [],
    },
    {
        id: "prov_005",
        name: "Dr. Chris Wilson",
        specialty: "Massage Therapy",
        profileImage: "https://i.pravatar.cc/150?img=30",
        location: "Denver, CO",
        clinicAddress: "202 Maple Ave, Denver, CO 80203",
        coordinates: { lat: 39.7450, lng: -104.9950 },
        tier: "Free",
        clinicianType: "Massage Therapist",
        gtCertifications: ["Essential"],
        services: ["Graston Technique", "Deep Tissue Massage"],
        languagesSpoken: ["English", "Mandarin"],
        patientTypes: ["Adult"],
        conditionsTreated: ["Neck Pain", "Back Pain"],
        rating: 4.9,
        reviewCount: 40,
        isFavorite: false,
        can_compare: false,
        views: 300,
        engagementScore: 50,
        trialStatus: 'N/A',
        churnRisk: false,
        activity: 40,
        accreditationLogos: [],
        testimonials: [],
        faqs: [],
    },
    {
        id: "prov_006",
        name: "Dr. Emily White",
        specialty: "Physical Therapy",
        profileImage: "https://i.pravatar.cc/150?img=50",
        location: "Boulder, CO",
        clinicAddress: "303 Cedar St, Boulder, CO 80302",
        coordinates: { lat: 40.0200, lng: -105.2600 },
        tier: "Premier",
        clinicianType: "Physical Therapist",
        gtCertifications: ["Advanced", "Essential"],
        services: ["Manual Therapy", "Graston Technique"],
        languagesSpoken: ["English", "German"],
        patientTypes: ["Adult", "Athletes"],
        conditionsTreated: ["Knee Pain", "Sports Injury"],
        rating: 4.8,
        reviewCount: 110,
        isFavorite: false,
        can_compare: true,
        views: 1800,
        engagementScore: 88,
        trialStatus: 'N/A',
        churnRisk: false,
        activity: 110,
        accreditationLogos: [],
        testimonials: [],
        faqs: [],
    },
    {
        id: "prov_007",
        name: "Dr. David Green",
        specialty: "Athletic Training",
        profileImage: "https://i.pravatar.cc/150?img=70",
        location: "Fort Collins, CO",
        clinicAddress: "404 Birch Ln, Fort Collins, CO 80521",
        coordinates: { lat: 40.5750, lng: -105.0750 },
        tier: "Preferred",
        clinicianType: "Athletic Trainer",
        gtCertifications: ["Essential"],
        services: ["Sports Massage", "Graston Technique"],
        languagesSpoken: ["English"],
        patientTypes: ["Athletes"],
        conditionsTreated: ["Ankle Rehab", "Sports Injury"],
        rating: 4.5,
        reviewCount: 50,
        isFavorite: false,
        can_compare: true,
        views: 600,
        engagementScore: 65,
        trialStatus: 'N/A',
        churnRisk: false,
        activity: 60,
        accreditationLogos: [],
        testimonials: [],
        faqs: [],
    },
    {
        id: "prov_008",
        name: "Dr. Olivia Black",
        specialty: "Chiropractic",
        profileImage: "https://i.pravatar.cc/150?img=80",
        location: "Colorado Springs, CO",
        clinicAddress: "505 Spruce Rd, Colorado Springs, CO 80903",
        coordinates: { lat: 38.8400, lng: -104.8300 },
        tier: "Premier",
        clinicianType: "Chiropractor",
        gtCertifications: ["GTS"],
        services: ["Spinal Adjustments", "Graston Technique"],
        languagesSpoken: ["English", "Spanish"],
        patientTypes: ["Adult"],
        conditionsTreated: ["Back Pain", "Headaches"],
        rating: 4.7,
        reviewCount: 80,
        isFavorite: false,
        can_compare: true,
        views: 1300,
        engagementScore: 80,
        trialStatus: 'N/A',
        churnRisk: false,
        activity: 90,
        accreditationLogos: [],
        testimonials: [],
        faqs: [],
    },
    {
        id: "prov_009",
        name: "Dr. Daniel Lee",
        specialty: "Physical Therapy",
        profileImage: "https://i.pravatar.cc/150?img=90",
        location: "Denver, CO",
        clinicAddress: "606 Willow Way, Denver, CO 80203",
        coordinates: { lat: 39.7300, lng: -104.9800 },
        tier: "Preferred",
        clinicianType: "Physical Therapist",
        gtCertifications: ["Advanced"],
        services: ["Myofascial Release", "Graston Technique"],
        languagesSpoken: ["English", "Hindi"],
        patientTypes: ["Geriatric"],
        conditionsTreated: ["Knee Pain", "Post-surgical Rehab"],
        rating: 4.2,
        reviewCount: 30,
        isFavorite: false,
        can_compare: true,
        views: 400,
        engagementScore: 60,
        trialStatus: 'N/A',
        churnRisk: false,
        activity: 50,
        accreditationLogos: [],
        testimonials: [],
        faqs: [],
    },
    {
        id: "prov_010",
        name: "Dr. Sophia Chen",
        specialty: "Pain Management",
        profileImage: "https://i.pravatar.cc/150?img=100",
        location: "Boulder, CO",
        clinicAddress: "707 Poplar Dr, Boulder, CO 80302",
        coordinates: { lat: 40.0100, lng: -105.2800 },
        tier: "Premier",
        clinicianType: "Medical Doctor",
        gtCertifications: ["GTS", "Essential"],
        services: ["Manual Therapy", "Graston Technique", "Acupuncture"],
        languagesSpoken: ["English", "Korean"],
        patientTypes: ["Adult"],
        conditionsTreated: ["Chronic Pain", "Neck Pain"],
        rating: 4.9,
        reviewCount: 150,
        isFavorite: true,
        can_compare: true,
        views: 2000,
        engagementScore: 95,
        trialStatus: 'N/A',
        churnRisk: false,
        activity: 130,
        accreditationLogos: [],
        testimonials: [],
        faqs: [],
    },
    {
        id: "prov_011",
        name: "Dr. Robert Kim",
        specialty: "Massage Therapy",
        profileImage: "https://i.pravatar.cc/150?img=11",
        location: "Fort Collins, CO",
        clinicAddress: "808 Fir Ct, Fort Collins, CO 80521",
        coordinates: { lat: 40.5900, lng: -105.0900 },
        tier: "Preferred",
        clinicianType: "Massage Therapist",
        gtCertifications: ["Advanced"],
        services: ["Neuromuscular Therapy", "Graston Technique"],
        languagesSpoken: ["English", "Italian"],
        patientTypes: ["Athletes"],
        conditionsTreated: ["Shoulder Pain", "Sports Injury"],
        rating: 4.7,
        reviewCount: 65,
        isFavorite: false,
        can_compare: true,
        views: 800,
        engagementScore: 75,
        trialStatus: 'N/A',
        churnRisk: false,
        activity: 75,
        accreditationLogos: [],
        testimonials: [],
        faqs: [],
    },
    {
        id: "prov_012",
        name: "Dr. Laura Garcia",
        specialty: "Chiropractic",
        profileImage: "https://i.pravatar.cc/150?img=22",
        location: "Colorado Springs, CO",
        clinicAddress: "909 Aspen Dr, Colorado Springs, CO 80903",
        coordinates: { lat: 38.8250, lng: -104.8150 },
        tier: "Free",
        clinicianType: "Chiropractor",
        gtCertifications: ["Essential"],
        services: ["Spinal Rehabilitation", "Graston Technique"],
        languagesSpoken: ["English", "Spanish"],
        patientTypes: ["Adult"],
        conditionsTreated: ["Back Pain", "Neck Pain"],
        rating: 4.3,
        reviewCount: 25,
        isFavorite: false,
        can_compare: false,
        views: 250,
        engagementScore: 45,
        trialStatus: 'N/A',
        churnRisk: false,
        activity: 30,
        accreditationLogos: [],
        testimonials: [],
        faqs: [],
    },
];