import { FullProviderProfile, ClinicianType, Language, Condition, PatientDemographic } from "@/types";

export const states = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"];

export const clinicianTypes: ClinicianType[] = ["Chiropractor", "Physical Therapist", "Athletic Trainer", "Massage Therapist", "Other"];

export const languages: Language[] = ["English", "Spanish", "French", "German", "Mandarin"];

export const radiusOptions = [5, 10, 25, 50, 100];

export const specialties = [
  "Chiropractic Care",
  "Physical Therapy", 
  "Sports Medicine",
  "Orthopedic Rehabilitation",
  "Manual Therapy"
];

export const conditions: Condition[] = ["Back Pain", "Neck Pain", "Headaches", "Sports Injuries", "Post-Surgical Rehab"];

export const patientDemographics: PatientDemographic[] = ["Athletes", "Pediatrics", "Geriatrics", "General Population"];

export const sortOptions = [
  { value: 'premier-first', label: 'Premier First' },
  { value: 'top-rated', label: 'Top Rated' },
  { value: 'most-reviewed', label: 'Most Reviewed' }
];

export const mockProviders: FullProviderProfile[] = [
    {
        id: "1",
        name: "Dr. John Doe",
        email: "john.doe@example.com",
        profileImage: "https://i.pravatar.cc/150?u=1",
        specialty: "Chiropractic Care",
        location: "New York, NY",
        clinicAddress: "123 Main St, New York, NY 10001",
        coordinates: { lat: 40.7128, lng: -74.0060 },
        phone: "(555) 123-4567",
        website: "https://johndoe.com",
        bio: "Dr. John Doe is a licensed chiropractor with over 15 years of experience specializing in spinal adjustments and the Graston Technique. He has helped thousands of patients recover from various musculoskeletal conditions.",
        tier: "Premier",
        clinicianType: "Chiropractor",
        gtCertifications: ["GTS", "Advanced"],
        services: ["Spinal Adjustments", "Graston Technique", "Rehabilitation"],
        languagesSpoken: ["English", "Spanish"],
        conditionsTreated: ["Back Pain", "Neck Pain", "Headaches"],
        patientTypes: ["Adults", "Seniors"],
        rating: 4.8,
        reviewCount: 127,
        trialStatus: "N/A",
        activity: 95,
        churnRisk: false,
        isFavorite: false,
        galleryImages: ["https://picsum.photos/400/300?random=1", "https://picsum.photos/400/300?random=2"],
        galleryVideos: ["https://www.youtube.com/embed/dQw4w9WgXcQ"],
        testimonials: [{ 
            id: "1",
            patientName: "Pro Athlete",
            rating: 5,
            text: "Dr. Doe got me back on the field in record time!",
            date: "2023-01-01",
            verified: true,
            quote: "Dr. Doe got me back on the field in record time!", 
            author: "Pro Athlete" 
        }],
        faqs: [{ 
            id: "1",
            question: "Do you take insurance?", 
            answer: "Yes, we accept most major insurance plans." 
        }],
        engagementScore: 85,
        views: 1250,
        can_compare: true,
        verificationBadges: ["Verified"],
        experience: "15 years",
        education: "Doctor of Chiropractic, Palmer College",
        linkedin: "https://linkedin.com/in/johndoe",
        certifications: ["GTS", "Advanced Graston Technique"]
    },
    {
        id: "2",
        name: "Sarah Johnson, PT",
        email: "sarah.johnson@example.com",
        profileImage: "https://i.pravatar.cc/150?u=2",
        specialty: "Physical Therapy",
        location: "Los Angeles, CA",
        clinicAddress: "456 Oak Ave, Los Angeles, CA 90210",
        coordinates: { lat: 34.0522, lng: -118.2437 },
        phone: "(555) 987-6543",
        website: "https://sarahjohnsonpt.com",
        bio: "Sarah Johnson is a dedicated physical therapist who combines traditional therapy techniques with innovative approaches like the Graston Technique to help her patients achieve optimal recovery.",
        tier: "Preferred",
        clinicianType: "Physical Therapist",
        gtCertifications: ["Essential"],
        services: ["Manual Therapy", "Graston Technique", "Therapeutic Exercise"],
        languagesSpoken: ["English"],
        conditionsTreated: ["Sports Injuries", "Post-Surgical Rehab"],
        patientTypes: ["Athletes", "Adults"],
        rating: 4.6,
        reviewCount: 89,
        trialStatus: "N/A",
        activity: 78,
        churnRisk: false,
        isFavorite: true,
        engagementScore: 72,
        views: 890,
        can_compare: true,
        experience: "8 years",
        education: "DPT, University of Southern California"
    },
    {
        id: "3",
        name: "Mike Chen, DPT",
        email: "mike.chen@example.com",
        profileImage: "https://i.pravatar.cc/150?u=3",
        specialty: "Sports Medicine",
        location: "Chicago, IL",
        clinicAddress: "789 Pine St, Chicago, IL 60601",
        coordinates: { lat: 41.8781, lng: -87.6298 },
        phone: "(555) 456-7890",
        website: "https://mikechenpt.com",
        bio: "Mike Chen specializes in sports medicine and has worked with professional athletes. His expertise in the Graston Technique has made him a sought-after therapist for sports-related injuries.",
        tier: "Preferred",
        clinicianType: "Physical Therapist",
        gtCertifications: ["GTS"],
        services: ["Graston Technique", "Therapeutic Exercises"],
        languagesSpoken: ["English", "Mandarin"],
        conditionsTreated: ["Sports Injuries"],
        patientTypes: ["Athletes"],
        rating: 4.9,
        reviewCount: 156,
        trialStatus: "N/A",
        activity: 92,
        churnRisk: false,
        isFavorite: false,
        engagementScore: 88,
        views: 1100,
        can_compare: true,
        experience: "12 years",
        education: "DPT, Northwestern University"
    },
    {
        id: "4",
        name: "Dr. Emily Rodriguez",
        email: "emily.rodriguez@example.com",
        profileImage: "https://i.pravatar.cc/150?u=4",
        specialty: "Chiropractic Care",
        location: "Houston, TX",
        clinicAddress: "321 Elm St, Houston, TX 77001",
        coordinates: { lat: 29.7604, lng: -95.3698 },
        phone: "(555) 321-0987",
        website: "https://emilyrodriguezdc.com",
        bio: "Dr. Emily Rodriguez focuses on holistic chiropractic care, integrating the Graston Technique with traditional spinal adjustments to provide comprehensive treatment for her patients.",
        tier: "Free",
        clinicianType: "Chiropractor",
        gtCertifications: ["Advanced"],
        services: ["Spinal Adjustments", "Graston Technique"],
        languagesSpoken: ["English", "Spanish"],
        conditionsTreated: ["Back Pain", "Neck Pain"],
        patientTypes: ["Adults", "Seniors"],
        rating: 4.4,
        reviewCount: 67,
        trialStatus: "N/A",
        activity: 65,
        churnRisk: true,
        isFavorite: false,
        engagementScore: 45,
        views: 320,
        can_compare: false,
        experience: "6 years",
        education: "Doctor of Chiropractic, Texas Chiropractic College"
    },
    {
        id: "5",
        name: "Lisa Wang, LMT",
        email: "lisa.wang@example.com",
        profileImage: "https://i.pravatar.cc/150?u=5",
        specialty: "Massage Therapy",
        location: "Seattle, WA",
        clinicAddress: "654 Cedar Blvd, Seattle, WA 98101",
        coordinates: { lat: 47.6062, lng: -122.3321 },
        phone: "(555) 654-3210",
        website: "https://lisawangmassage.com",
        bio: "Lisa Wang is a licensed massage therapist who incorporates the Graston Technique into her practice to provide effective soft tissue mobilization and pain relief.",
        tier: "Premier",
        clinicianType: "Massage Therapist",
        gtCertifications: ["Essential"],
        services: ["Graston Technique", "Deep Tissue Massage"],
        languagesSpoken: ["English", "Mandarin"],
        rating: 4.9,
        reviewCount: 203,
        trialStatus: "N/A",
        activity: 88,
        churnRisk: false,
        isFavorite: false,
        engagementScore: 92,
        views: 1450,
        can_compare: true,
        experience: "10 years",
        education: "Licensed Massage Therapist, Seattle Massage School"
    },
    {
        id: "6",
        name: "Dr. Robert Kim, PT",
        email: "robert.kim@example.com",
        profileImage: "https://i.pravatar.cc/150?u=6",
        specialty: "Orthopedic Rehabilitation",
        location: "Miami, FL",
        clinicAddress: "987 Coral Way, Miami, FL 33101",
        coordinates: { lat: 25.7617, lng: -80.1918 },
        phone: "(555) 789-0123",
        website: "https://robertkimpt.com",
        bio: "Dr. Robert Kim specializes in orthopedic rehabilitation and has extensive experience using the Graston Technique for post-surgical recovery and chronic pain management.",
        tier: "Preferred",
        clinicianType: "Physical Therapist",
        gtCertifications: ["Advanced", "Essential"],
        services: ["Manual Therapy", "Graston Technique"],
        languagesSpoken: ["English"],
        conditionsTreated: ["Post-Surgical Rehab", "Sports Injuries"],
        patientTypes: ["Adults", "Athletes"],
        rating: 4.7,
        reviewCount: 134,
        trialStatus: "N/A",
        activity: 81,
        churnRisk: false,
        isFavorite: true,
        engagementScore: 78,
        views: 980,
        can_compare: true,
        experience: "14 years",
        education: "DPT, University of Miami"
    },
    {
        id: "7",
        name: "Jessica Martinez, ATC",
        email: "jessica.martinez@example.com",
        profileImage: "https://i.pravatar.cc/150?u=7",
        specialty: "Athletic Training",
        location: "Denver, CO",
        clinicAddress: "147 Mountain View Dr, Denver, CO 80201",
        coordinates: { lat: 39.7392, lng: -104.9903 },
        phone: "(555) 147-2580",
        website: "https://jessicamartinezatc.com",
        bio: "Jessica Martinez is a certified athletic trainer who works with high school and college athletes, using the Graston Technique as part of her injury prevention and rehabilitation programs.",
        tier: "Free",
        clinicianType: "Athletic Trainer",
        gtCertifications: ["Essential"],
        services: ["Sports Massage", "Graston Technique"],
        languagesSpoken: ["English", "Spanish"],
        conditionsTreated: ["Sports Injuries"],
        patientTypes: ["Athletes", "Adolescents"],
        rating: 4.5,
        reviewCount: 78,
        trialStatus: "N/A",
        activity: 72,
        churnRisk: false,
        isFavorite: false,
        engagementScore: 65,
        views: 540,
        can_compare: false,
        experience: "5 years",
        education: "MS Athletic Training, University of Colorado"
    },
    {
        id: "8",
        name: "Dr. David Thompson",
        email: "david.thompson@example.com",
        profileImage: "https://i.pravatar.cc/150?u=8",
        specialty: "Chiropractic Care",
        location: "Phoenix, AZ",
        clinicAddress: "258 Desert Rose Ave, Phoenix, AZ 85001",
        coordinates: { lat: 33.4484, lng: -112.0740 },
        phone: "(555) 258-3690",
        website: "https://davidthompsondc.com",
        bio: "Dr. David Thompson has been practicing chiropractic care for over two decades, with a special focus on the Graston Technique for treating chronic musculoskeletal conditions.",
        tier: "Preferred",
        clinicianType: "Chiropractor",
        gtCertifications: ["GTS"],
        services: ["Spinal Adjustments", "Graston Technique"],
        languagesSpoken: ["English"],
        conditionsTreated: ["Back Pain", "Neck Pain", "Headaches"],
        patientTypes: ["Adults", "Seniors"],
        rating: 4.6,
        reviewCount: 145,
        trialStatus: "N/A",
        activity: 79,
        churnRisk: false,
        isFavorite: false,
        engagementScore: 73,
        views: 820,
        can_compare: true,
        experience: "22 years",
        education: "Doctor of Chiropractic, Palmer College"
    },
    {
        id: "9",
        name: "Amanda Foster, PT",
        email: "amanda.foster@example.com",
        profileImage: "https://i.pravatar.cc/150?u=9",
        specialty: "Manual Therapy",
        location: "Boston, MA",
        clinicAddress: "369 Commonwealth Ave, Boston, MA 02101",
        coordinates: { lat: 42.3601, lng: -71.0589 },
        phone: "(555) 369-1470",
        website: "https://amandafosterpt.com",
        bio: "Amanda Foster is a physical therapist who specializes in manual therapy techniques, with advanced training in the Graston Technique for treating fascial restrictions and scar tissue.",
        tier: "Free",
        clinicianType: "Physical Therapist",
        gtCertifications: ["Advanced"],
        services: ["Myofascial Release", "Graston Technique"],
        languagesSpoken: ["English"],
        conditionsTreated: ["Post-Surgical Rehab", "Sports Injuries"],
        patientTypes: ["Adults"],
        rating: 4.3,
        reviewCount: 92,
        trialStatus: "N/A",
        activity: 68,
        churnRisk: true,
        isFavorite: false,
        engagementScore: 52,
        views: 410,
        can_compare: false,
        experience: "7 years",
        education: "DPT, Boston University"
    },
    {
        id: "10",
        name: "Dr. Steven Lee, MD",
        email: "steven.lee@example.com",
        profileImage: "https://i.pravatar.cc/150?u=10",
        specialty: "Sports Medicine",
        location: "San Francisco, CA",
        clinicAddress: "741 Golden Gate Ave, San Francisco, CA 94101",
        coordinates: { lat: 37.7749, lng: -122.4194 },
        phone: "(555) 741-8520",
        website: "https://stevenleesportsmed.com",
        bio: "Dr. Steven Lee is a sports medicine physician who integrates the Graston Technique into his comprehensive treatment approach for athletes and active individuals.",
        tier: "Premier",
        clinicianType: "Medical Doctor",
        gtCertifications: ["GTS", "Essential"],
        services: ["Manual Therapy", "Graston Technique", "Acupuncture"],
        languagesSpoken: ["English"],
        conditionsTreated: ["Sports Injuries", "Back Pain"],
        patientTypes: ["Athletes", "Adults"],
        rating: 4.8,
        reviewCount: 189,
        trialStatus: "N/A",
        activity: 94,
        churnRisk: false,
        isFavorite: true,
        engagementScore: 89,
        views: 1320,
        can_compare: true,
        experience: "18 years",
        education: "MD, UCSF School of Medicine"
    },
    {
        id: "11",
        name: "Rachel Green, LMT",
        email: "rachel.green@example.com",
        profileImage: "https://i.pravatar.cc/150?u=11",
        specialty: "Massage Therapy",
        location: "Portland, OR",
        clinicAddress: "852 Pine Street, Portland, OR 97201",
        coordinates: { lat: 45.5152, lng: -122.6784 },
        phone: "(555) 852-9630",
        website: "https://rachelgreenmassage.com",
        bio: "Rachel Green is a licensed massage therapist with advanced training in neuromuscular therapy and the Graston Technique, helping clients achieve pain relief and improved mobility.",
        tier: "Preferred",
        clinicianType: "Massage Therapist",
        gtCertifications: ["Advanced"],
        services: ["Neuromuscular Therapy", "Graston Technique"],
        languagesSpoken: ["English"],
        conditionsTreated: ["Back Pain", "Neck Pain"],
        patientTypes: ["Adults", "Seniors"],
        rating: 4.7,
        reviewCount: 167,
        trialStatus: "N/A",
        activity: 83,
        churnRisk: false,
        isFavorite: false,
        engagementScore: 76,
        views: 920,
        can_compare: true,
        experience: "11 years",
        education: "Licensed Massage Therapist, Oregon School of Massage"
    },
    {
        id: "12",
        name: "Dr. Mark Wilson",
        email: "mark.wilson@example.com",
        profileImage: "https://i.pravatar.cc/150?u=12",
        specialty: "Chiropractic Care",
        location: "Atlanta, GA",
        clinicAddress: "963 Peachtree St, Atlanta, GA 30301",
        coordinates: { lat: 33.7490, lng: -84.3880 },
        phone: "(555) 963-7410",
        website: "https://markwilsondc.com",
        bio: "Dr. Mark Wilson combines traditional chiropractic techniques with modern approaches like the Graston Technique to provide effective treatment for spinal conditions and rehabilitation.",
        tier: "Free",
        clinicianType: "Chiropractor",
        gtCertifications: ["Essential"],
        services: ["Spinal Rehabilitation", "Graston Technique"],
        languagesSpoken: ["English"],
        conditionsTreated: ["Back Pain", "Neck Pain"],
        patientTypes: ["Adults"],
        rating: 4.2,
        reviewCount: 85,
        trialStatus: "N/A",
        activity: 61,
        churnRisk: true,
        isFavorite: false,
        engagementScore: 48,
        views: 380,
        can_compare: false,
        experience: "9 years",
        education: "Doctor of Chiropractic, Life University"
    }
];