export type Condition = string;
export type Language = string;

export interface FullProviderProfile {
  id: string;
  name?: string | null;
  specialty?: string | null;
  bio?: string | null;
  experience?: string | null;
  education?: string | null;
  profile_image?: string | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  linkedin?: string | null;
  facebook?: string | null;
  instagram?: string | null;
  twitter?: string | null;
  services?: string[] | null;
  certifications?: string[] | null;
  location?: string | null;
  clinic_address?: string | null;
  coordinates?: { lat: number; lng: number } | null;
  gt_certifications?: string[] | null;
  verification_badges?: string[] | null;
  accreditation_logos?: any | null;
  languages_spoken?: Language[] | null;
  patient_types?: string[] | null;
  conditions_treated?: Condition[] | null;
  rating?: number | null;
  review_count?: number | null;
  is_favorite?: boolean | null;
  tier?: 'Premier' | 'Preferred' | 'Free' | null;
  clinician_type?: string | null;
  updated_at?: string | null;
  gallery_images?: string[] | null;
  gallery_videos?: string[] | null;
  testimonials?: any[] | null;
  faqs?: any[] | null;
  can_compare?: boolean | null;
  views?: number | null;
  accepting_new_patients?: boolean | null;
}