// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kkjaghivhckgcpamdtrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtramFnaGl2aGNrZ2NwYW1kdHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDA3OTIsImV4cCI6MjA3MDA3Njc5Mn0.ZRLuuziOZA-VspPV3cAwAMuTBbHRenPcumJJBW9vyfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);